/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LocaleRouteRouteImport } from './$locale/route'
import { Route as IndexRouteImport } from './index'
import { Route as LocaleAuthRouteRouteImport } from './$locale/auth/route'
import { Route as LocalePublicRouteRouteImport } from './$locale/_public/route'
import { Route as LocalePublicIndexRouteImport } from './$locale/_public/index'
import { Route as LocaleAuthLoginIndexRouteImport } from './$locale/auth/login/index'
import { Route as LocalePublicPostIndexRouteImport } from './$locale/_public/post/index'
import { Route as LocalePublicPostCreateIndexRouteImport } from './$locale/_public/post/create/index'
import { Route as LocalePublicPostPostIdIndexRouteImport } from './$locale/_public/post/$postId/index'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthRouteRoute = LocaleAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePublicRouteRoute = LocalePublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePublicIndexRoute = LocalePublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalePublicRouteRoute,
} as any)
const LocaleAuthLoginIndexRoute = LocaleAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any)
const LocalePublicPostIndexRoute = LocalePublicPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => LocalePublicRouteRoute,
} as any)
const LocalePublicPostCreateIndexRoute =
  LocalePublicPostCreateIndexRouteImport.update({
    id: '/post/create/',
    path: '/post/create/',
    getParentRoute: () => LocalePublicRouteRoute,
  } as any)
const LocalePublicPostPostIdIndexRoute =
  LocalePublicPostPostIdIndexRouteImport.update({
    id: '/post/$postId/',
    path: '/post/$postId/',
    getParentRoute: () => LocalePublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocalePublicRouteRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/': typeof LocalePublicIndexRoute
  '/$locale/post/': typeof LocalePublicPostIndexRoute
  '/$locale/auth/login/': typeof LocaleAuthLoginIndexRoute
  '/$locale/post/$postId/': typeof LocalePublicPostPostIdIndexRoute
  '/$locale/post/create/': typeof LocalePublicPostCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocalePublicIndexRoute
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/post': typeof LocalePublicPostIndexRoute
  '/$locale/auth/login': typeof LocaleAuthLoginIndexRoute
  '/$locale/post/$postId': typeof LocalePublicPostPostIdIndexRoute
  '/$locale/post/create': typeof LocalePublicPostCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/_public': typeof LocalePublicRouteRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/_public/': typeof LocalePublicIndexRoute
  '/$locale/_public/post/': typeof LocalePublicPostIndexRoute
  '/$locale/auth/login/': typeof LocaleAuthLoginIndexRoute
  '/$locale/_public/post/$postId/': typeof LocalePublicPostPostIdIndexRoute
  '/$locale/_public/post/create/': typeof LocalePublicPostCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/auth'
    | '/$locale/'
    | '/$locale/post/'
    | '/$locale/auth/login/'
    | '/$locale/post/$postId/'
    | '/$locale/post/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/auth'
    | '/$locale/post'
    | '/$locale/auth/login'
    | '/$locale/post/$postId'
    | '/$locale/post/create'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_public'
    | '/$locale/auth'
    | '/$locale/_public/'
    | '/$locale/_public/post/'
    | '/$locale/auth/login/'
    | '/$locale/_public/post/$postId/'
    | '/$locale/_public/post/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_public': {
      id: '/$locale/_public'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalePublicRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_public/': {
      id: '/$locale/_public/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalePublicIndexRouteImport
      parentRoute: typeof LocalePublicRouteRoute
    }
    '/$locale/auth/login/': {
      id: '/$locale/auth/login/'
      path: '/login'
      fullPath: '/$locale/auth/login/'
      preLoaderRoute: typeof LocaleAuthLoginIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/_public/post/': {
      id: '/$locale/_public/post/'
      path: '/post'
      fullPath: '/$locale/post/'
      preLoaderRoute: typeof LocalePublicPostIndexRouteImport
      parentRoute: typeof LocalePublicRouteRoute
    }
    '/$locale/_public/post/create/': {
      id: '/$locale/_public/post/create/'
      path: '/post/create'
      fullPath: '/$locale/post/create/'
      preLoaderRoute: typeof LocalePublicPostCreateIndexRouteImport
      parentRoute: typeof LocalePublicRouteRoute
    }
    '/$locale/_public/post/$postId/': {
      id: '/$locale/_public/post/$postId/'
      path: '/post/$postId'
      fullPath: '/$locale/post/$postId/'
      preLoaderRoute: typeof LocalePublicPostPostIdIndexRouteImport
      parentRoute: typeof LocalePublicRouteRoute
    }
  }
}

interface LocalePublicRouteRouteChildren {
  LocalePublicIndexRoute: typeof LocalePublicIndexRoute
  LocalePublicPostIndexRoute: typeof LocalePublicPostIndexRoute
  LocalePublicPostPostIdIndexRoute: typeof LocalePublicPostPostIdIndexRoute
  LocalePublicPostCreateIndexRoute: typeof LocalePublicPostCreateIndexRoute
}

const LocalePublicRouteRouteChildren: LocalePublicRouteRouteChildren = {
  LocalePublicIndexRoute: LocalePublicIndexRoute,
  LocalePublicPostIndexRoute: LocalePublicPostIndexRoute,
  LocalePublicPostPostIdIndexRoute: LocalePublicPostPostIdIndexRoute,
  LocalePublicPostCreateIndexRoute: LocalePublicPostCreateIndexRoute,
}

const LocalePublicRouteRouteWithChildren =
  LocalePublicRouteRoute._addFileChildren(LocalePublicRouteRouteChildren)

interface LocaleAuthRouteRouteChildren {
  LocaleAuthLoginIndexRoute: typeof LocaleAuthLoginIndexRoute
}

const LocaleAuthRouteRouteChildren: LocaleAuthRouteRouteChildren = {
  LocaleAuthLoginIndexRoute: LocaleAuthLoginIndexRoute,
}

const LocaleAuthRouteRouteWithChildren = LocaleAuthRouteRoute._addFileChildren(
  LocaleAuthRouteRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocalePublicRouteRoute: typeof LocalePublicRouteRouteWithChildren
  LocaleAuthRouteRoute: typeof LocaleAuthRouteRouteWithChildren
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocalePublicRouteRoute: LocalePublicRouteRouteWithChildren,
  LocaleAuthRouteRoute: LocaleAuthRouteRouteWithChildren,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
